name: Deploy do Site Pessoal na AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload para o S3 (com delete)
        run: |
          aws s3 sync ./ s3://martinsnicolas.com --delete \
            --exclude ".git/*" \
            --exclude ".github/*"

      - name: Invalidar cache do CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3VFK09KWT5XAS \
            --paths "/*"