name: Terraform Apply + Atualização Bucket S3
on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    terraform-apply:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: terraform
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Credenciais AWS
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::601920909369:role/resume-cloud-challenge-actions
            aws-region: us-east-1
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
        
        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate
        
        - name: Terraform Apply
          run: terraform apply --auto-approve
        
    atualizacao-bucket-s3:
        runs-on: ubuntu-latest
        needs: terraform-apply
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Credencias AWS
              uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume:  arn:aws:iam::601920909369:role/resume-cloud-challenge-actions
                aws-region: us-east-1
            
            - name: Atualizar o Bucket S3
              run: |
               aws s3 sync ./site s3://nicolas-static-website --delete \
               --exclude ".git/*" \
               --exclude ".github/*"
            
            - name: Invalidar Cache CloudFront
              run: |
               aws cloudfront create-invalidation \
                 --distribution-id ${{ secrets.CLOUD_FRONT_ID }}\
                 --paths "/*"