name: Terraform Plan
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: terraform 
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Credenciais AWS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::601920909369:role/resume-cloud-challenge-actions
            aws-region: us-east-1
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
        
        - name: Terraform Init
          run: terraform init
        
        - name: Terraform Validate
          run: terraform validate
        
        - name: Terraform Plan
          run: terraform plan